spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    #  servlet:
    #    multipart:
    #      max-file-size: 30Mb
    #      max-request-size: 30M
    cache:
      type: redis
    jackson:
      serialization:
        INDENT_OUTPUT: true
      date-format: yyyy-MM-dd HH:mm:ss
      joda-date-time-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: NON_NULL
      time-zone: GMT+8
    mvc:
      #    hiddenmethod:
      #      filter:
      #        enabled: false
      #    formcontent:
      #      filter:
      #        enabled: false
      pathmatch:
        use-suffix-pattern: true
        use-registered-suffix-pattern: true
      view:
        prefix: classpath:/jsp/
        suffix: .jsp
  application:
    name: usp-ums
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.web.reactive.ReactiveWebServerFactoryAutoConfiguration
      - org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketMessagingAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.reactive.WebSocketReactiveAutoConfiguration
      - com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
server:
  servlet:
    context-path: /api