#服务器端口
env: staging
server:
  port: 29020
  url: http://ums-staging.youshupai.com/api
  undertow:
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
logging:
  config: classpath:logback-dev.xml
fake:
  pre: FAKE-
token:
  admin:
    expire: 14
  fake:
    expire: 1
ip:
  expire: 2
my:
  token:
qrnum: 5

spring:
  mvc:
    view:
      suffix: .do
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf656rcueks797xsg9o.mysql.rds.aliyuncs.com:3306/usp_ums_staging?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: usp_ums
    password: YE0S8jRxKhN
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.211.170:8848,172.26.211.171:8848,172.26.211.172:8848
        namespace: 5ec829e1-ab7f-45d0-b940-d02632d9ae5c
  redis:
    host: 172.19.162.178
    port: 6379
    database: 6
    password:
    timeout: 15000
    lettuce:
      pool:
        max-active: 8 # 最大连接数量，默认8，能够同时建立的最大连接数
        max-idle: 8 # 最大空闲连接数量，默认8，空闲连接数大于maxIdle时，将进行回收
        max-wait: 1000 # 最大阻塞等待时间，默认-1
        min-idle: 5 # 最小空闲数，默认0，低于minIdle时，将创建新的连接
  cache:
    type: redis
    #认证缓存时间5反正
    #默认换粗那时间1小时
    timeout: "{auth:300, default:3600}"
  nats:
    js:
      nats-urls:
        - nats://172.26.211.170:4228
        - nats://172.26.211.171:4228
        - nats://172.26.211.172:4228
      jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJJVlVDWDJPV1dWUFg0MkhPWDI2TkRTUldOV0VFREpDVTM2RVNINU9RVFY0VEJVWldEM0FRIiwiaWF0IjoxNjMxNTg2MTYzLCJpc3MiOiJBQjZKQjNWVEI2SDRDNUw3RTdBUFNPWFBaRUIzRFdMVEc1T1VCNk5IV1hUNVFQMjRXNllERlNTUSIsIm5hbWUiOiJ1cHMiLCJzdWIiOiJVRE9OWE1BTFdXTVpSNFlTSktVUEpRR1c3T1pPVEs0WVFVVDJKRUdUWFU2UzJRVFFJT0xJQk9TUCIsIm5hdHMiOnsicHViIjp7fSwic3ViIjp7fSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwidHlwZSI6InVzZXIiLCJ2ZXJzaW9uIjoyfX0.VTqxxsPFlqm45TX1drqw_wGaMKjumVbQsO51Zmx-z4F51OW_ZB6lCOJCB1-R62o5fhik45pAIHwo7dW6Z8jHCQ
      nkey: SUAP4CBUERD4NK3M4EOOJZHIWIGQZODSNSVC6VVCK7ALEQW4VEPAYDVLVQ


  # 输出
  # 配置ANSI输出（可以是“detect”，“always”，“never”）-->“检测”，“永远”，“从不”
  output:
    ansi:
      enabled: DETECT
  # JavaMailSender
  mail:
    host: smtp.qq.com
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
email:
  sender:
  receiver:

mybatis-plus:
  #  config-location: classpath:META-INF/mybatis-config.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeEnumsPackage: com.usp.ums.enums
  type-aliases-package: com.usp.ums.entity
  type-handlers-package: com.usp.framework.mybatis,com.usp.ums.entity
  global-config:
    banner: false
    refresh: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
      #数据库大写下划线转换
      #capital-mode: true
      #super-mapper-class: com.zhixin.framework.mapper.BaseMapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-behavior: FULL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  cloud:
    subscribed-services: usp-basis
  application:
    name: usp-ums
  registry:
    #    address: spring-cloud://localhost # 注册中心
    #如果要使用自己创建的命名空间可以使用下面2种方式
    #dubbo.registry.address = nacos://127.0.0.1:8848?namespace=5cbb70a5-xxx-xxx-xxx-d43479ae0932
    #dubbo.registry.parameters.namespace=5cbb70a5-xxx-xxx-xxx-d43479ae0932
    address: nacos://172.26.211.170:8848?namespace=5ec829e1-ab7f-45d0-b940-d02632d9ae5c&backup=172.26.211.171:8848,172.26.211.172:8848 # 注册中心
    check: false
  protocols:
    dubbo:
      name: dubbo # 服务协议
      port: 29120 # 服务端口
  consumer:
    check: false


knife4j:
  enable: true
  cors: true
  markdowns: classpath:markdown2x/*

jwt:
  #  header: Authorization
  token:
    secret: 3AHLGP6wlAki0pBuQg3p19Z6TWEIGQfc2ayJY326
    #    7天
    #    expiration: 604800

    #    一年
    expiration: 31536000

xxl:
  job:
    admin:
      addresses: http://job-staging.yspdev.com/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-ums-staging
      address:
      ip:
      port: 29220
      logpath:
      logretentiondays: 30

boss-token:
  redis:
    host: 172.19.162.178
    port: 6379
    database: 0
    password:
    timeout: 15000s
    lettuce:
      pool:
        max-active: 8 # 最大连接数量，默认8，能够同时建立的最大连接数
        max-idle: 8 # 最大空闲连接数量，默认8，空闲连接数大于maxIdle时，将进行回收
        max-wait: 1000 # 最大阻塞等待时间，默认-1
        min-idle: 5 # 最小空闲数，默认0，低于minIdle时，将创建新的连接